### ISSUE TITLE
Error: enum Index must have at least one member

### ISSUE THREAD

**Issue by taylorthurlow** [spoved/entitas.cr#2]
I'm getting this error around line 70 of `generator.cr` both while trying to run a program similar to the hello world example, and while trying to run `crystal docs`.

Any suggestions?

**Comment by kalinon** [comment]
So this is due to you not having any components. I really should add that to the documentation... Anyway, if you have a component declared, such as this:

```crystal
@[Context(Example)]
class ExampleComponent < Entitas::Component
  prop :message, String, default: ""

  def to_s(io)
    io << message
  end
end
```

it should generate documentation.

**Comment by kalinon** [comment]
Since there is so much code that is auto generated, it is also recomended to include `./lib/entitas/src/entitas.cr` when generating documentation for your application/lib. Like so:

```shell
crystal docs ./lib/entitas/src/entitas.cr ./src/
```

Ive updated the README to include this information.

**Comment by taylorthurlow** [comment]
Ah ok I see the problem. What would you suggest doing as far as getting documentation for the code that isn't generated at compile-time?
