### ISSUE TITLE
Update examples/inter_context_communication.cr

### ISSUE THREAD

**Issue by Nephos** [spoved/entitas.cr#4]
Hello everyone,

First I love your work thanks a lot. I'm using it for some personal project. However I'm not a veteran of ECS, I'm still learning alot.

I saw `examples/inter_context_communication.cr` is a little bit dated, I think they have been update on the framework since then. Do you mind updating it if you can spare some time?

:love_you_gesture:

**Comment by kalinon** [comment]
Awesome! Glad someone is using it! Yes i think i never finished that example, which is based off https://github.com/sschmid/Entitas-CSharp/wiki/Inter-context-communication-in-Entitas-0.39.0

I will try to look at it this week and get an example working.

**Comment by kalinon** [comment]
@Nephos I have finished the example! you can see it here: https://github.com/spoved/entitas.cr/tree/master/examples/inter_context_communication

**Comment by Nephos** [comment]
Oh my my ! Thanks this is amazing, thanks a lot !
